# Generated by Django 5.2.6 on 2025-10-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_concours_souhaite_user_etablissement_origine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='concours_souhaite',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='etablissement_origine',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='niveau_etude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenoms',
            field=models.CharField(default='', max_length=100),
        ),
    ]
